### ISSUE TITLE
Copy to Clipboard Feature for Code Snippets

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/design-system-starter#12]
**Enhancement:**
We would like to add a button either above or below code snippets to allow users to quickly copy the code.

- The HTML for the button can be added to `src/markup/patterns/drizzle/partials/item.hbs`.
- The SCSS for the button can be added to `src/scss/design-system-interface.scss`.
- The JS for the button can be added to `src/js/design-system-interface.js`.

![Buttons___YOURNAMEHERE_Design_System](https://user-images.githubusercontent.com/2486846/66431615-4d4cab00-e9ea-11e9-830e-b4ca2c013b32.png)

**Comment by iAmNathanJ** [comment]
@kaseybon mind if I take this one?

**Comment by kaseybon** [comment]
It's all yours @iAmNathanJ
