### ISSUE TITLE
Unordered List partial is an <ol>

### ISSUE THREAD

**Issue by ethanmuller** [sparkbox/design-system-starter#8]
The Design System Starter has a few patterns in it to begin with. There's a pattern for an Unordered List, but it's marked up as an `ol`. Oops! It should be marked up as a `ul` instead.

That pattern lives here: https://github.com/sparkbox/design-system-starter/blob/master/src/markup/patterns/components/defaults/list--unordered.hbs

**Comment by erin-sparkbox** [comment]
I can do this one!
