### ISSUE TITLE
External SVG Polyfill for Internet Explorer

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/design-system-starter#9]
**The Problem:**
SVG `use` elements can reference other elements defined in the same SVG or in another SVG that is embedded on the page without any issues but our sprite sheet references an external  SVG which needs some polyfill love in order to work in Internet Explorer.

We have used [svg4everybody](https://github.com/jonathantneal/svg4everybody) in other projects with success.

**The Fix:**
1. Install `svg4everybody` as a dependency `npm install svg4everybody --save`
2. Initialize in `src/js/index.js` with the following code:
    ``` 
    const svg4everybody = require('svg4everybody');
    svg4everybody();
    ```
3. Confirm that the SVG sprites work by running the project and viewing the buttons page (http://localhost:3000/patterns/components/buttons.html) in any version of IE (use IE 11 for best results). The variants dropdown should now include the chevron icon.
    ![Buttons___YOURNAMEHERE_Design_System](https://user-images.githubusercontent.com/2486846/66427715-900a8500-e9e2-11e9-9ff6-53c4421648a7.png)

**Comment by heatherdesigns** [comment]
I'll take this one! 💃

**Comment by bryanbraun** [comment]
I noticed that this was merged in https://github.com/sparkbox/design-system-starter/pull/27, so I'll go ahead and close this issue. 👍
